---
    - name: rbenv | check ruby $ruby_version installed
      shell: RBENV_ROOT=${rbenv_root} rbenv versions | grep $ruby_version
      register: ruby_installed
      ignore_errors: yes

    - name: rbenv | install ruby $ruby_version
      shell: RBENV_ROOT=${rbenv_root} rbenv install $ruby_version
      when: ruby_installed|failed

    - name: rbenv | set global ruby $ruby_version
      shell: RBENV_ROOT=${rbenv_root} rbenv global $ruby_version
      when: ruby_installed|failed

    - name: rbenv | rehash
      shell: RBENV_ROOT=${rbenv_root} rbenv rehash
      when: ruby_installed|failed

    - name: rbenv | set gemrc
      copy: src=files/gemrc dest=/root/.gemrc owner=root group=root mode=0644
